### ISSUE TITLE
Failed to write bootloader configuration

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/TigerOS#58] opened 2017-10-14 05:15 UTC
@axk4545  @ct-martin When installing TigerOS GNOME edition to my physical laptop, the bootloader fails to install properly.

When I select the exact same configuration on the official Fedora 26 distro, the installation goes fine.

**Comment by ct-martin** [comment] 2017-10-14 06:08
Debugged w/ @Tjzabel - Confirmed issue exists and involves UEFI, BIOS install works fine.

@axk4545 going to assign this to you since this is your territory.

**Comment by axk4545** [comment] 2017-10-14 13:58
@ct-martin Will look into it soo.

**Comment by Tjzabel** [comment] 2017-10-14 18:19
UPDATE: Currently this issue is present both in the Cinnamon and GNOME TigerOS installations.

**Comment by linux-modder** [comment] 2017-10-15 01:04
@axk4545 @Tjzabel confirm installer / install image have grub2-efi package installed.  If so, file bug upstream with both anaconda and grub2 developers.

**Comment by axk4545** [comment] 2017-10-15 01:08
@linux-modder @Tjzabel @ct-martin it is in the ks.  please confirm it is actually in the resultant image.

**Comment by axk4545** [comment] 2017-10-15 01:13
per @linux-modder add --efi to LMC command in build scripts.

**Comment by ct-martin** [comment] 2017-10-15 01:16
@axk4545 Can confirm grub2-efi is installed on the liveusb, will rebuild with —efi and then we can retest

**Comment by ct-martin** [comment] 2017-10-15 02:27
"livemedia-creator: error: unrecognized arguments: --efi"
(cc @axk4545 @linux-modder )

**Comment by axk4545** [comment] 2017-10-16 20:04
This makes me think we should also test on Mac as they have a special EFI implementation

**Comment by axk4545** [comment] 2017-10-17 03:42
@axk4545 Attempted an install with a TigerOS live USB burned with Fedora Media Writer. Same result

**Comment by linux-modder** [comment] 2017-10-19 18:26
@ct-martin on live doesn't mean it's in the squashfs tho the squahsfs is what is rsync'd off for install on a non netinstall iso

Will check the present ks today and see if I can find a bug in the logic or usage.

**Comment by ct-martin** [comment] 2017-10-19 18:29
@linux-modder do you have a command I can run on the live to test if it's there?

**Comment by axk4545** [comment] 2017-10-22 19:35
@Tjzabel will test once we get a build. currently blocked on gstreamer dep issues upstream

**Comment by axk4545** [comment] 2017-10-25 20:05
@Tjzabel can I have the logs from the install and the exact error message? the logs will be at `/tmp/anaconda.log`, `/tmp/program.log` and `/tmp/syslog` on the installer system(when running from the install disk/live usb). they can also be pulled from the installed system in `/var/log/anaconda` if you skip the GRUB step and complete the install.

**Comment by axk4545** [comment] 2017-10-25 20:58
It might be an issue with the anaconda install class. I will look at it.

**Comment by Tjzabel** [comment] 2017-10-28 01:12
Soooo The UEFI build works!! How should I proceed? This issue may be available to close.

**Comment by axk4545** [comment] 2017-10-28 01:13
@Tjzabel test it repeatedly. also if you have the old one with logs grab them please.

**Comment by ct-martin** [comment] 2017-10-28 01:32
So, what did we change between then and now?

**Comment by linux-modder** [comment] 2017-10-28 01:51
@Tjzabel what iso was tested?  was it bare metal or virtual? so I can secondarily confirm and possibly peck at the logs and such to iron out the actual part that fixed this.

**Comment by Tjzabel** [comment] 2017-10-28 01:53
@linux-modder The latest ISO was tested using a UEFI build box. It was installed bare-metal.

**Comment by Tjzabel** [comment] 2017-10-28 01:54
There is no /boot/efi partition now, which is interesting

**Comment by axk4545** [comment] 2017-10-28 01:58
@Tjzabel Make sure it wasn't done in BIOS mode by mistake

**Comment by Tjzabel** [comment] 2017-10-28 01:59
@axk4545 How should I go about finding that out.

**Comment by axk4545** [comment] 2017-10-28 04:50
@Tjzabel @linux-modder @ct-martin I attempted a UEFI install and was able to reproduce the issue. Please see the attached logs. Also looping @AdamWill in on this as he expressed interest in helping me debug this
[logs.zip](https://github.com/RITlug/TigerOS/files/1423938/logs.zip)

**Comment by axk4545** [comment] 2017-10-28 04:53
This install used [linuxmodder.iso](https://tigeros.ritlug.com/isos/linuxmodder.iso)

**Comment by axk4545** [comment] 2017-10-28 04:56
Output of `lsblk` on the effected disk:
NAME             MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sdb                8:16   0 74.5G  0 disk 
├─sdb1             8:17   0  200M  0 part 
├─sdb2             8:18   0    1G  0 part 
└─sdb3             8:19   0 73.3G  0 part 
  ├─tigeros-swap 253:3    0  7.5G  0 lvm  
  ├─tigeros-home 253:4    0 21.6G  0 lvm  
  └─tigeros-root 253:5    0 44.3G  0 lvm

**Comment by axk4545** [comment] 2017-11-03 15:39
Will check @AdamWill on any issues the logs may reveal

**Comment by axk4545** [comment] 2017-11-03 15:47
@Tjzabel's install was accidentally done in BIOS mode

**Comment by Josh1147582** [comment] 2017-11-03 17:18
I installed the latest build (linuxmodder.iso) in Virtualbox, forcing EFI. `program.log` indicates that `grub2-mkconfig` is returning a nonzero status:

[](https://i.imgur.com/qCE4Llu.png)

When I looked in `/boot/efi/EFI/` after the install, there was no `tigeros` directory. I'm guessing this is the issue.

The `grub2-efi` package creates `boot/efi/EFI/fedora` automatically. If the issue is our EFI directory isn't being created, we should either use the `fedora` directory, or rename `fedora` to `tigeros`.

I'm gonna remove our EFI change, rebuild, and see if the install completes successfully.

**Comment by axk4545** [comment] 2017-11-04 02:02
@Josh1147582 Let us know if it work and we can make the fix.

**Comment by AdamWill** [comment] 2017-11-04 02:15
Ah, that's a reasonable theory. Other install classes that change `efi_dir`, I think, come along with a different set of bootloader packages that provide the appropriate directory. E.g. RHEL changes it to (I think) "redhat", and of course ships with grub2 packages that provide bootloader bits in `/boot/efi/EFI/redhat`.

**Comment by axk4545** [comment] 2017-11-04 02:17
@AdamWill so do we have a need to keep it as TigerOS as far as conflicting or IP stuff? It would be nice to not repackage grub stuff

**Comment by AdamWill** [comment] 2017-11-04 02:19
I can't speak Officially Legally, but I'd be really surprised if we considered that a branding violation. Obviously if you want to be *parallel installable* with real-Fedora, changing it is useful.

**Comment by axk4545** [comment] 2017-11-04 02:20
@AdamWill ok. will talk it over with @RITlug/tigeros-team

**Comment by axk4545** [comment] 2017-11-10 17:05
http://pkgs.fedoraproject.org/cgit/rpms/grub2.git/tree/grub2.spec?h=f22
So it appears that GRUB sets the efidir at build time in the specfile. Would be nice to see if this can be split out.

**Comment by axk4545** [comment] 2017-11-17 18:23
We have implemented a temporary fix with #71 and opened #79 to track making a more permanent fix

**Closed by axk4545** 2017-11-17 18:23 UTC
Labels: bug, meeting, priority:critical, retest

**Comment by Rtoax** [comment] 2022-06-22 07:25
I got 

```
The following error occurred while installing the boot loader. The system will not be bootable, Would you like to ignore this and continue with installation?

failed to write boot loader configuration
```
